-- SQL Script to Remove Unused Columns from pre_computed_features
-- Generated by analyze_unused_columns.py
-- WARNING: BACKUP DATABASE BEFORE RUNNING!

BEGIN;

ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_form_last_5_games;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_current_state;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_expected_next_state;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_markov_momentum;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_performance_volatility;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_state_confidence;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_state_duration;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_state_stability;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS away_team_transition_entropy;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS h2h_last_updated;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_form_last_5_games;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_current_state;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_expected_next_state;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_markov_momentum;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_performance_volatility;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_state_confidence;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_state_duration;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_state_stability;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS home_team_transition_entropy;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS markov_match_prediction_confidence;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS markov_outcome_probabilities;
ALTER TABLE pre_computed_features DROP COLUMN IF EXISTS weather_temp_f;

-- Verify the changes
SELECT column_name FROM information_schema.columns 
WHERE table_name = 'pre_computed_features' 
ORDER BY ordinal_position;

-- Uncomment the next line to commit changes
-- COMMIT;
ROLLBACK; -- Remove this line when ready to commit